import Foundation

/// Hard limits imposed by `MSSticker`, plus the tuning constants derived
/// from them. Values confirmed against the CDN in Task 0.
public enum StickerLimits {
    /// `MSSticker` rejects files above 500 KB. 500,000 is the conservative
    /// decimal reading of that limit.
    public static let maxBytes = 500_000
    public static let minDimension = 100
    public static let maxDimension = 618

    /// Side length of the square canvas every sticker is rendered onto.
    ///
    /// Task 0 measured that Discord's `?size=` only downscales, and that emoji
    /// are frequently non-square and sometimes below `minDimension` (76x61 was
    /// observed). So normalization is mandatory, not cosmetic.
    ///
    /// 256 trades sharpness for headroom against the extension's 40-120 MB
    /// ceiling: ~20 visible cells cost ~5 MB decoded here versus ~20 MB at 512.
    /// Validated by Task 11's scroll test — if the extension is still killed,
    /// drop this to 128.
    public static let canvasSize = 256
    /// Used when the `canvasSize` render still exceeds `maxBytes`.
    public static let fallbackCanvasSize = 128

    /// Side length of the square canvas animated stickers are rendered onto.
    ///
    /// Matches `canvasSize`. It was 128 while animated stickers were encoded
    /// as APNG, which made them render at half the size of static ones in a
    /// conversation — visibly, and the first thing device testing found.
    ///
    /// 256 became affordable by encoding as GIF instead. Measured on real
    /// 7TV emotes, APNG costs **3-4x** the bytes of GIF for identical content,
    /// because it stores full RGBA per frame while GIF palettizes and
    /// LZW-compresses. That premium bought nothing here: every animated source
    /// this app ingests — Discord's CDN and 7TV's alike — **is already a GIF**,
    /// so re-encoding to APNG paid four times over to store colours and alpha
    /// the source never had.
    ///
    /// | Emote | APNG (old) | GIF (now) |
    /// |---|---|---|
    /// | AlienDance, 66 frames | 128px, 48 frames | 256px, 64 frames |
    /// | WAYTOODANK, 75 frames | 128px, 48 frames | 256px, 32 frames |
    /// | BillyApprove, 90 frames | 128px, **24** frames | 192px, 32 frames |
    public static let animatedCanvasSize = 256

    /// Used when a rung at `animatedCanvasSize` still exceeds `maxBytes`.
    public static let midAnimatedCanvasSize = 192

    /// Fallback canvas for animated stickers whose frame count is punishing.
    public static let smallAnimatedCanvasSize = 128

    /// Frames beyond this are dropped evenly, with their delays redistributed
    /// so total loop duration is unchanged.
    ///
    /// Raised from 48 with the move to GIF. Real 7TV emotes commonly run
    /// **41-90 frames**, so a 48-frame cap was visibly dropping motion on the
    /// majority of animated emotes — the second thing device testing found.
    public static let maxAnimatedFrames = 64

    /// The reduced frame budget used by the lower rungs of the ladder.
    public static let reducedAnimatedFrames = 32

    /// Last resort before an animated sticker is rejected outright.
    public static let minAnimatedFrames = 16

    public static let recentsLimit = 16
    public static let downloadConcurrency = 5

    /// Hard ceiling on either dimension of a fetched image, checked from
    /// metadata before anything is decoded. A byte cap does not bound a
    /// bitmap: flat artwork at 8000x6000 compresses under 10 MB and decodes
    /// to ~192 MB, past the window where the extension is killed.
    public static let maxSourcePixelDimension = 4096

    /// Ceiling on bytes accepted from a single picked photo or fetched link.
    public static let maxSourceBytes = 10_000_000

    /// Photos loadable in one pick. Unlimited selection is not survivable:
    /// raw picked bytes are resident before anything can be downsampled, and
    /// 20 photos at 3 MB already crosses the extension's 40 MB floor.
    public static let maxPhotoSelection = 30

    /// Concurrent photo loads. Matches `downloadConcurrency`'s reasoning:
    /// peak memory is per-in-flight-item, so the cap is the bound.
    public static let photoLoadConcurrency = 4

    /// Ceiling on emoji parsed from a single `DSTK1` transfer payload.
    /// Machine-generated by the desktop companion, so — unlike pasted
    /// Discord markup — it is not bounded by what a human is willing to
    /// select and copy, and needs its own cap the way every other ingest
    /// path already has one.
    public static let maxPayloadEmoji = 500

    /// Ceiling on a sticker name's length, in characters, for names that
    /// arrive from outside this device rather than being typed here.
    public static let maxStickerNameLength = 64
}
